print("Hello world")
print("PIZDEC")
print("sudo")
print("зэвщорафкпэжщорздпвыаф")
print("sdfg hoidfgoh")
print("Hello world")
print("PIZDEC")
print("sudo")
print("зэвщорафкпэжщорздпвыаф")
print("sdfg hoidfgoh")
print("sdlj")